### ISSUE TITLE
Python3 support for Datadog-RDS-Enhanced

### ISSUE THREAD

**Issue by mvanholsteijn** [DataDog/datadog-serverless-functions#187]
**Describe what happened:**
The datadog rds enhanced log report is still configured to use the Python2.7 runtime.

**Describe what you expected:**
that the Python3.7 runtime is used.

**Steps to reproduce the issue:**
Just deploy the Datadog-RDS-Enhanced application -> https://eu-central-1.console.aws.amazon.com/lambda/home?region=eu-central-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:464622532012:applications/Datadog-RDS-Enhanced

**Comment by entscheidungsproblem** [comment]
Are there any updates for this issue? The [cloudformation template](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/rds_enhanced_monitoring/rds-enhanced-sam-template.yaml#L21) is still using python2.7 which is causing an alert in Security Hub since it is not using the latest runtime (python3.8, python3.7 or python3.6).

**Comment by entscheidungsproblem** [comment]
This has been resolved by [this PR](https://github.com/DataDog/datadog-serverless-functions/pull/353 )

**Comment by ghost** [comment]
I've just deployed from Serverless Repo, and it's failing with various errors, e.g.:

```bash
Unknown application error occurred

[ERROR] JSONDecodeError: Extra data: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 72, in <module>
    datadog_keys = _datadog_keys()
  File "/var/task/lambda_function.py", line 31, in _datadog_keys
    )['Plaintext'])
  File "/var/lang/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
```

**Comment by ghost** [comment]
Can someone confirm that RDS Enchanted metrics Lambda is now working on python 3.7 runtimes?

**Comment by ghost** [comment]
I've just managed to execute it, will submit a PR shortly.

**Comment by RaphaelAllier** [comment]
Hello, 

Doing some clean up so will close this issue. This [PR](https://github.com/DataDog/datadog-serverless-functions/pull/670) should have fixed the errors mentioned in the above comments. It seems AWS sometimes doesn't provide JSON valid payloads
