### ISSUE TITLE
lambda errors - timout 10min no debug logging

### ISSUE THREAD

**Issue by diepes** [DataDog/datadog-serverless-functions#426]
**Describe what happened:**
when aws datadog-forwarder lambda runs every  so often a run fails, by running to the maximum time.
added env var  DD_LOG_LEVEL  debug
increased max timeout to 10min.

**Describe what you expected:**
See some debug for the long running events not just the short ones.

**Steps to reproduce the issue:**
Not sure, happening in our environment, with PrivateLink DD endpoints.

Log messages in CloudWatch / Log groups  /aws/lambda/datadog-forwarder  e.g.
```
/var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
--
RequestsDependencyWarning)
START RequestId: 72be2647-3758-4464-a79d-0ac9e518cab2 Version: $LATEST
/var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
RequestsDependencyWarning)
END RequestId: 72be2647-3758-4464-a79d-0ac9e518cab2
REPORT RequestId: 72be2647-3758-4464-a79d-0ac9e518cab2	Duration: 601100.79 ms	Billed Duration: 601000 ms	Memory Size: 256 MB	Max Memory Used: 42 MB
2021-02-23T04:41:47.519Z 72be2647-3758-4464-a79d-0ac9e518cab2 Task timed out after 601.10 seconds

```

Other invocations work, and contain debug logs, some in same logsteam. 
```

START RequestId: 87629282-1f96-4994-81e0-c7eb7318b338 Version: $LATEST
--
[DEBUG]	2021-02-23T05:45:06.640Z	e8005494-1849-4cfd-a216-59163ff63870	[dd.trace_id=0 dd.span_id=0]	Flushing metrics in thread
[DEBUG]	2021-02-23T05:45:06.640Z	e8005494-1849-4cfd-a216-59163ff63870	[dd.trace_id=0 dd.span_id=0]	No metrics to flush. Continuing.
[DEBUG]	2021-02-23T05:45:06.640Z	e8005494-1849-4cfd-a216-59163ff63870	[dd.trace_id=0 dd.span_id=0]	No distributions to flush. Continuing.
[DEBUG]	2021-02-23T05:45:06.640Z	e8005494-1849-4cfd-a216-59163ff63870	[dd.trace_id=0 dd.span_id=0]	No events to flush. Continuing.
[DEBUG]	2021-02-23T05:45:06.643Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8037176827931374364 dd.span_id=6522576434000810659]	Not submitting enhanced metric invocations because enhanced metrics are disabled
[DEBUG]	2021-02-23T05:45:06.643Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8037176827931374364 dd.span_id=6522576434000810659]	extracted dd trace context {'trace-id': '8460795402960033906', 'parent-id': '5837228094213247506', 'sampling-priority': '-1', 'source': 'xray'}
[DEBUG]	2021-02-23T05:45:06.643Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	correlation ids set
[DEBUG]	2021-02-23T05:45:06.644Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	datadog_lambda_wrapper _before() done
[DEBUG]	2021-02-23T05:45:06.644Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Received Event:{     "awslogs": {         "data": "H4sIAAAAAxxxxxxAA=="     } }
[DEBUG]	2021-02-23T05:45:06.644Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Parsed event type: awslogs
[DEBUG]	2021-02-23T05:45:06.645Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Extracted 0 metrics, 0 traces, and 23 logs
[DEBUG]	2021-02-23T05:45:06.645Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Forwarding 23 logs
[DEBUG]	2021-02-23T05:45:06.656Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Initialized http client for logs intake: <host: api-pvtlink.logs.datadoghq.com, port: 443, url: https://api-pvtlink.logs.datadoghq.com:443/v1/input/ca7fxxxxe0d8, no_ssl: False, skip_ssl_validation: False, timeout: 10>
[DEBUG]	2021-02-23T05:45:06.659Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=0 dd.span_id=0]	Starting new HTTPS connection (1): api-pvtlink.logs.datadoghq.com:443
[DEBUG]	2021-02-23T05:45:06.660Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Forwarded log batch: ["{\"id\": \"359947xxxxxx59104\", \"timestamp\": 1614058428161, \"message\": \"START RequestId: 541d2f05-8af5-47eb-bf9f-f88633e303b9 Version: $LATEST\\n\", \"aws\": {\"awslogs\": {\"logGroup\": \"/aws/lambda/order-xxxxService\", \"logStream\": \"2021/02/23/[$LATEST]d12d05afb2984d5bb16ee40074c32db0\", \"owner\": \"69xxxxx\"}, \"function_version\": \"$LATEST\", \"invoked_function_arn\": \"arn:aws:lambda:ap-southeast-2:691xxxx:function:datadog-forwarder\"}, \"lambda\": {\"arn\": 
...
... 100 more debug lines
...
\"}"]
[DEBUG]	2021-02-23T05:45:07.505Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=0 dd.span_id=0]	https://api-pvtlink.logs.datadoghq.com:443 "POST /v1/input/ca...d8 HTTP/1.1" 200 2
[DEBUG]	2021-02-23T05:45:07.507Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Forwarding 0 metrics
[DEBUG]	2021-02-23T05:45:07.508Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.duration 0.13544 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxx', 'aws_account:69xxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.508Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.billed_duration 0.136 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxx', 'aws_account:69xxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.508Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.max_memory_used 140.0 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxx', 'aws_account:69xxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.508Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.estimated_cost 2.4666712e-06 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxx', 'aws_account:69xxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.508Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.duration 0.15411000000000002 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxx', 'aws_account:69xxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.508Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.billed_duration 0.155 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxx', 'aws_account:69xxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.508Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.max_memory_used 140.0 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxxx', 'aws_account:69xxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.509Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Submitting metric aws.lambda.enhanced.estimated_cost 2.7833385000000004e-06 ['memorysize:1024', 'cold_start:false', 'region:ap-southeast-2', 'account_id:69xxxxxx', 'aws_account:69xxxxxx', 'functionname:order-provisioning-v2-test4-pollenergyservice', 'stage:test4', 'aws_cloudformation_logical-id:pollenergyservicelambdafunction', 'aws_cloudformation_stack-id:arn:aws:cloudformation:ap-southeast-2:69xxxxxx:stack/order-provisioning-v2-test4/71316560-7879-11ea-9bd1-0aca1a52eebc', 'aws_cloudformation_stack-name:order-provisioning-v2-test4']
[DEBUG]	2021-02-23T05:45:07.509Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	No metrics to flush. Continuing.
[DEBUG]	2021-02-23T05:45:07.509Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	Flush #78 sending 11 distributions
[DEBUG]	2021-02-23T05:45:07.711Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	https://pvtlink.api.datadoghq.com:443 "POST /api/v1/distribution_points?api_key=ca...d8 HTTP/1.1" 202 16
[INFO]	2021-02-23T05:45:07.712Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	202 POST https://pvtlink.api.datadoghq.com/api/v1/distribution_points (203.0692ms)
[DEBUG]	2021-02-23T05:45:07.712Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	No events to flush. Continuing.
[DEBUG]	2021-02-23T05:45:07.712Z	87629282-1f96-4994-81e0-c7eb7318b338	[dd.trace_id=8460795402960033906 dd.span_id=5837228094213247506]	datadog_lambda_wrapper _after() done
END RequestId: 87629282-1f96-4994-81e0-c7eb7318b338
REPORT RequestId: 87629282-1f96-4994-81e0-c7eb7318b338	Duration: 1070.98 ms	Billed Duration: 1071 ms	Memory Size: 256 MB	Max Memory Used: 85 MB

```

**Comment by tianchu** [comment]
@diepes I suggest you set the timeout of the Forwarder Lambda to a lower value (in fact the default is 2 min), so it fails fast in case a network connection hangs (for various reasons), and CW will try. resending the logs with the Forwarder.

To figure out what it's blocked on, do you have debug logs from a long invocation?

**Comment by diepes** [comment]
@tianchu i will set the timeout back to 2min (from 10min) to reduce the impact of the datadog lambda failing, was just to test if it is taking  longer that 2min to respond..
 
 the first message above is one of many with the timeout, it contain no debug info, although there is other successful messages, the 2nd example, in same logstream (lambda execution) that works in <2sec and contains debug output.

I logged the ticket, as there seems to be something broken with the datadog logging, how can the lambda with debug logging enabled timeout after 10min without logging anything for that event ?

This makes it very hard to debug what is happening for the occasions when something going wrong in the lambda.

**Comment by tianchu** [comment]
Was `DD_LOG_LEVEL` set to `debug` when the first log was generated? Because the forwarder at least should log the event it receives when debugging (the first thing it does): https://github.com/DataDog/datadog-serverless-functions/blob/615c4e7a43d65e542fa83ac5908d47f7601baab3/aws/logs_monitoring/lambda_function.py#L378

If you are certain the debug logging was enabled or you still see new invocations timing out without writing any useful debugging logs, that means the function must stuck on the initialization, then it's likely the api key validation api call timing out https://github.com/DataDog/datadog-serverless-functions/blob/615c4e7a43d65e542fa83ac5908d47f7601baab3/aws/logs_monitoring/lambda_function.py#L77

If you want, you can easily build your own version of the forwarder and add more debugging lines https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#contributing.

**Comment by tianchu** [comment]
In fact when looking at the code, I noticed that the api call to validate the api key does not have a timeout, which might be why the forwarder hangs forever https://github.com/DataDog/datadog-serverless-functions/blob/615c4e7a43d65e542fa83ac5908d47f7601baab3/aws/logs_monitoring/lambda_function.py#L77. I'll add a timeout to that request and release a new version.

**Comment by tianchu** [comment]
@diepes can you try out the new version https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.28.5?

**Comment by diepes** [comment]
@tianchu thanks for looking into it, i will try it, and let you know.

**Comment by diepes** [comment]
![image](https://user-images.githubusercontent.com/96414/109549940-829fee80-7b33-11eb-8e6a-c682a9fb235e.png)
@tianchu i deployed 3.28.5, built it locally.
It runs and uploads graphs but still intermittently hits timeout 2min.

I will add some debugs and update.

From the screen shot below of a timeout logged, you can see it was only the first event, after that the lambda seem to run fine.
![image](https://user-images.githubusercontent.com/96414/109550795-9ac43d80-7b34-11eb-806d-3cdad471a005.png)

**Comment by tianchu** [comment]
@diepes Can you set env var `DD_LOG_LEVEL` to `debug`? From your screenshot, it doesn't seem that debug logging was enabled. I ask because in that same commit I also added some debugging log lines specifically targeting the cold start to help narrow down the issue https://github.com/DataDog/datadog-serverless-functions/pull/428/files

**Comment by diepes** [comment]
@tianchu , yes the DD_LOG_LEVEL  debug env var was missing, added it now.
might log to much sensitive info, lets see.

**Comment by diepes** [comment]
@tianchu had to leave some info out.
For the initial timeouts they seem to happen before the new debug, i will try to add some more later.

### Note: Initial invocations 1-2 just end, and 3-7 timeout 130000ms (2min + 10 sec)
![image](https://user-images.githubusercontent.com/96414/109560767-25ab3500-7b41-11eb-8e89-23ad0fbbb658.png)

### Note: And then it starts working (Same logfile/lambda)
![image](https://user-images.githubusercontent.com/96414/109560811-2e037000-7b41-11eb-8e35-de09e8f69e79.png)

### Note: See msg below "Validating the Datadog API key"
![image](https://user-images.githubusercontent.com/96414/109560826-3196f700-7b41-11eb-9b89-91f449774d95.png)
#

**Comment by diepes** [comment]
It seems when a lambda start there is initial invocations that hit the 2min timeout, and then it starts working and i see the validate log message.

Let me add some more logging to the imports to see what is visible.

**Comment by diepes** [comment]
To github.com:diepes/datadog-serverless-functions.git
   f4cf666..638c965  issue426-lambda-timeouts-120s -> issue426-lambda-timeouts-120s
  
After adding some more debug, the timeouts when the datadog-serverless-function lambda starts seem to be related to the loading of the settings.py.

In screen shot below lambda_function.py loads, and last msg in CloudWatch from additional debugging before lambda_function.py starts again is  "2021-03-02T16:44:48.515+13:00 **settings.py DD_API_KEY...**" this is followed by "2021-03-02T16:44:48.515+13:00 **[INFO] 2021-03-02T03:44:35.420Z Found credentials in environment variables.**" probably a boto3 messages. Then END and REPORT  Task timed out after 130000ms.

![image](https://user-images.githubusercontent.com/96414/109594926-75592300-7b78-11eb-9f07-1d2b20e68f08.png)

After a couple of more START messages it starts working.
2021-03-02T16:47:09.517+13:00 | settings.py settings.py Start/entered
2021-03-02T16:47:09.517+13:00 | settings.py DD_API_KEY_...
2021-03-02T16:47:09.656+13:00 | [INFO]	2021-03-02T03:47:09.655Z		Found credentials in environment variables.
2021-03-02T16:47:09.974+13:00 | settings.py settings.py End/Exit
2021-03-02T16:47:09.974+13:00 | lambda_function.py import from settings done - get logger
2021-03-02T16:47:09.975+13:00 | [INFO]	2021-03-02T03:47:09.974Z		Starting lambda_function.py 1/7 - loaded conf/env - DD_...
...
...
2021-03-02T16:47:22.040+13:00 | REPORT RequestId: 310516c4-a91d-4774-a35e-a0afcfdf46e5	Duration: 1099.98 ms	Billed Du...

**Comment by diepes** [comment]
After adding boto3 timeout 10 sec.
I got one startup of lambda 95sec with error msg.
After logging 15 of them each around 90sec time to fail, it loads fine and continues fine servicing events  ???
```
[ERROR] ConnectTimeoutError: Connect timeout on endpoint URL: "https://secretsmanager.ap-southeast-2.amazonaws.com/"
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 11, in <module>
    from settings import (
  File "/var/task/settings.py", line 196, in <module>
    DD_API_KEY = boto3.client("secretsmanager", config=boto3_config).get_secret_value(SecretId=SECRET_ARN)[
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 663, in _make_api_call
    operation_model, request_dict, request_context)
  File "/var/runtime/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/runtime/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/runtime/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/var/runtime/botocore/endpoint.py", line 256, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/var/runtime/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/runtime/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/runtime/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/runtime/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/var/runtime/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/var/runtime/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/var/runtime/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/var/runtime/botocore/httpsession.py", line 287, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)

```

**Comment by tianchu** [comment]
hmm, that feels like an AWS issue? Definitely not expecting the forwarder to timeout on the SecretsManager call. Perhaps you could try adjust `max_attempts` and `retry_mode` https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html?

**Comment by diepes** [comment]
@tianchu yes is agree, at least with the boto3 timeout set there is now an error in the lambda logs.
Will investigate possible AWS issues with Security groups and routing, still not sure how it manages to eventually start working.

**Comment by diepes** [comment]
@tianchu ok issue resolved.   Was the Private VPC endpoint (secretsmanager.ap-southeast-2.amazonaws.com) that was not reachable from the lambda subnet.

Here is PR with the boto3 timeout, that generated the error in the logs.
https://github.com/DataDog/datadog-serverless-functions/pull/430
