### ISSUE TITLE
Error: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by x-504** [DataDog/datadog-serverless-functions#772]
**Describe what happened:**
Hello,

I have create a lambda function for forwarding logs from AWS Cloudwatch Log Groups to Datadog.

It is using python 3.11
I am using this version: https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.108.0

On the logs from the lambda function I am having the following error

```
[INFO]	2024-04-22T16:21:48.727Z		[dd.trace_id=0 dd.span_id=0]	Configured ddtrace instrumentation for 1 integration(s). The following modules have been patched: logging
Configured ddtrace instrumentation for 1 integration(s). The following modules have been patched: logging
START RequestId: ceb362a6-a5e0-4423-a4d3-813aeb5f090a Version: $LATEST
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] OSError: /var/task/trace_forwarder/bin/trace-intake.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/python/datadog_lambda/wrapper.py", line 232, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/lambda_function.py", line 73, in datadog_forwarder
    init_forwarder(function_prefix)
  File "/var/task/lambda_function.py", line 107, in init_forwarder
    forwarder = Forwarder(function_prefix)
  File "/var/task/forwarder.py", line 42, in __init__
    self.trace_connection = TraceConnection(
  File "/var/task/trace_forwarder/connection.py", line 22, in __init__
    self.lib = cdll.LoadLibrary("
{}
/bin/trace-intake.so".format(dir))
  File "/var/lang/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
  File "/var/lang/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
```
**Describe what you expected:**
I expect the lambda function works properly and forward the logs to DataDog

**Steps to reproduce the issue:**
Create a Lambda function for Logging from AWS Cloudwatch Log Groups

Please let me know if you need any further information

**Comment by x-504** [comment]
Closing this issue. The problem was that I was using the wrong release package artifact
