### ISSUE TITLE
ListTagsForResource fails to get log group tags after v3.115.0

### ISSUE THREAD

**Issue by selina-yosh** [DataDog/datadog-serverless-functions#824]
**Describe what happened:**
We use aws-dd-forwarder-3.115.0 to forward cloudwatch logs to datadog, and we get the following error:
"Failed to get log group tags"
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the ListTagsForResource operation: Invalid resourceArn

When we use aws-dd-forwarder-3.114.0, there is no error.

----------------
[ERROR]	2024-07-22T03:22:22.805Z	fb3a2610-d2b1-4d0c-a736-0e02bce8ac0b	[dd.trace_id=2685132624149447776 dd.span_id=8357311845160155887]	Failed to get log group tags
Traceback (most recent call last):
  File "/var/task/caching/cloudwatch_log_group_cache.py", line 174, in _get_log_group_tags
    response = self.cloudwatch_logs_client.list_tags_for_resource(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the ListTagsForResource operation: Invalid resourceArn

**Describe what you expected:**
We expected no error.

Cause:
We see in aws-dd-forwarder-3.115.0, 
boto3 API is changed from “ListTagsLogGroup” to “ListTagsForResource”，but boto3 version(1.10.33) is not changed to support the API “ListTagsForResource”, caused this error.

v3.115.0 release note:
https://github.com/DataDog/datadog-serverless-functions/releases

boto3 v1.10.33 support list:
https://boto3.amazonaws.com/v1/documentation/api/1.10.33/reference/services/logs.html#client
We can see "list_tags_log_group" supported, "list_tag_for_resource" not support.

**Steps to reproduce the issue:**
Using aws-dd-forwarder-3.115.0(perheps version after v3.115.0) to forward cloudwatch loggroup will reproduce the issue.

**Comment by badrobit** [comment]
We are still seeing this on `aws-dd-forwarder-3.122.0`

**Comment by duncanista** [comment]
Just created a new forwarder, I see this error too

**Comment by badrobit** [comment]
We updated to the latest we have available (`3.130.0`) and the error is still being logged for us.
